config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :products do
    resources :comments
  end

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @product = Product.find(params[:product_id])
    @comment = @product.comments.create(comment_params)
    redirect_to product_path(@product)
  end

  def destroy
    @product = Product.find(params[:product_id])
    @comment = @product.comments.find(params[:id])
    @comment.destroy
    redirect_to product_path(@product)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @product = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to products_path
  end

  private
    def product_params
      params.require(:product).permit(:title, :text)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Kommentierender:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Kommentar:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Kommentar löschen', [comment.product, comment],
              method: :delete,
              data: { confirm: 'Sind Sie sich sicher' } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @product, @product.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :Kommentierender %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :Kommentar %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projekt3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model: @product, local: true do |form| %>

  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@product.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :Produktname %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :Produktbeschreibung %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/products/edit.html.erb
<h1>Bearbeite das Produkt</h1>

<%= render 'form' %>

<%= link_to 'Zurück', product_path %>

app/views/products/index.html.erb
<h1>Liste aller Produkte</h1>
<%= link_to 'Neues Produkt', new_product_path %>

<table>
  <tr>
    <th>Produktname</th>
    <th>Produktbeschreibung</th>
    <th></th>
  </tr>

  <% @product.each do |product| %>
    <tr>
      <td><%= product.title %></td>
      <td><%= product.text %></td>
      <td><%= link_to 'Zeigen', product_path(product) %></td>
      <td><%= link_to 'Bearbeiten', edit_product_path(product) %></td>
      <td><%= link_to 'Destroy', product_path(product), method: :delete, data: {confirm: 'Sind Sie sich sicher?'} %></td>
    </tr>
  <% end %>
</table>

app/views/products/new.html.erb
<h1>Neues Produkt</h1>

<%= render 'form' %>

<%= link_to 'Zurück', products_path %>

app/views/products/show.html.erb
<p>
  <strong>Produktname:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Produktbeschreibung:</strong>
  <%= @product.text %>
</p>

<h2>Kommentare:</h2>
<%= render @product.comments %>

<h2>Füge einen Kommentar hinzu:</h2>
<%= render 'comments/form' %>

<%= link_to 'Bearbeiten', edit_product_path(@product) %> |
<%= link_to 'Zurück', products_path %>

app/views/welcome/index.html.erb
<h1>Die Produktbewertungsseite</h1>

<%= link_to 'Zur Produktbewertung', controller: 'products'  %>